#!/usr/bin/env zsh

root=/home/e640846/Sites/n3blog
cd $root
for langue in fr en; do
    \cp -r ../webroot/content/* content/html/$langue
    for fic in content/html/$langue/**/*.html; do
        mv -f $fic $(dirname $fic)/$(basename $fic .html).md
    done
    \rm -f content/html/$langue/**/*.xml
    cp recup.pl recup$langue.pl
    [[ $langue = "fr" ]] && other=en
    [[ $langue = "en" ]] && other=fr
    echo 'replaceminim( "'$langue':","::", 1);' >> recup$langue.pl
    echo 'replaceminim( "'$other':","::", 0);' >> recup$langue.pl
    echo 'replaceminim( "<'$langue'>", "</'$langue'>", 1);' >> recup$langue.pl
    echo 'replaceminim( "<'$other'>", "</'$other'>", 0);' >> recup$langue.pl
    echo 'replaceminim( "!!'$langue'!!", "!!!!", 1);' >> recup$langue.pl
    echo 'replaceminim( "!!'$other'!!", "!!!!", 0);' >> recup$langue.pl
    echo 's#date:#created_at:#' >> recup$langue.pl
    perl -pi recup$langue.pl content/html/$langue/**/*(.)
done
