#!/usr/bin/env zsh

if [[ $HOST = "YiMac.local" ]]; then
    cd $HOME/Sites/webroot
    git co master
    [[ ! $? ]] && { exit 1 }
    git pull 
    [[ ! $? ]] && { exit 1 }
    ./tasks/recompile
    if git status | grep 'nothing to commit'>/dev/null 2>&1; then 
    else
        git commit -a -m "regeneration" 
    fi
    git push heroku master
else
    ssh yimac ./Sites/webroot/tasks/hpublish
fi
